[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = [
  "solmate/=lib/solmate/src/",
  "forge-std/=lib/forge-std/src/"
]
verbosity = 1
evm_version = "london"

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
scroll = "https://rpc.scroll.io"
scroll_sepolia = "https://sepolia-rpc.scroll.io"

[etherscan]
scroll = { key = "48EQKFV3BTGJN8DRY4E2UNMMYZIITYFSPY", chain=534352  }
scroll_sepolia = { key = "DBZ4A6JQKWUIY98ZU743DNI84MSIQNNN6A", chain=534351 }